__author__ = 'etseng@pacb.com'


KMER_SIZE = 30
DEBUG_FLAG = False
EXPECTED_ERR_RATE = 1
NX_CYCLE_DETECTION = False
MAX_SPLIT_IN_SIZE = 20
MAX_POST_SPLIT_IN_SIZE = 50
MAX_RECUR_DEPTH = 2
RANDOMLY_RESOLVE_DANGLES = False